ktor:
  deployment:
    port: 8080
  application:
    modules:
      - di.AppModuleKt.configureDI
      - di.AppModuleKt.configureMonitoring
      - di.AppModuleKt.configureSecurity
      - di.AppModuleKt.configureSerialization
      - di.AppModuleKt.configureRoute
      - di.AppModuleKt.configureDatabase

